### ISSUE TITLE
when import tranzlate,it`s error!

### ISSUE THREAD

**Issue by chenpaner** [ti-oluwa/tranzlate#5]
Python: Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\Blender Program\stable\blender-4.2.0\4.2\python\Lib\site-packages\tranzlate\__init__.py", line 9, in <module>
    from .translator import Translator, add_translatable_html_tag
  File "G:\Blender Program\stable\blender-4.2.0\4.2\python\Lib\site-packages\tranzlate\translator.py", line 12, in <module>
    from asgiref.sync import sync_to_async
ModuleNotFoundError: No module named 'asgiref'

Try in Tranzlate 0.0.2 !

**Comment by ti-oluwa** [comment]
Apologies for the late response. 
So sorry about this. This was a silly error of omission. I built this a side project while working on a gig and decide to publish it. I didn't remember to include the `asgiref` library as a dependency and didn't notice as it was installed globally on my machine. I've fixed this in v0.0.3 #6
